# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_engine.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'game_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11game_engine.proto\"9\n\x0cPlayerAction\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\n\n\x02\x64x\x18\x02 \x01(\x05\x12\n\n\x02\x64y\x18\x03 \x01(\x05\" \n\x0bViewRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\":\n\x04\x43\x65ll\x12\x0e\n\x06pseudo\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x05\x12\t\n\x01y\x18\x04 \x01(\x05\"l\n\x0cMoveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05new_x\x18\x03 \x01(\x05\x12\r\n\x05new_y\x18\x04 \x01(\x05\x12\x1c\n\rvisible_cells\x18\x05 \x03(\x0b\x32\x05.Cell\",\n\x0cViewResponse\x12\x1c\n\rvisible_cells\x18\x01 \x03(\x0b\x32\x05.Cell2a\n\x11GameEngineService\x12$\n\x04Move\x12\r.PlayerAction\x1a\r.MoveResponse\x12&\n\x07GetView\x12\x0c.ViewRequest\x1a\r.ViewResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERACTION']._serialized_start=21
  _globals['_PLAYERACTION']._serialized_end=78
  _globals['_VIEWREQUEST']._serialized_start=80
  _globals['_VIEWREQUEST']._serialized_end=112
  _globals['_CELL']._serialized_start=114
  _globals['_CELL']._serialized_end=172
  _globals['_MOVERESPONSE']._serialized_start=174
  _globals['_MOVERESPONSE']._serialized_end=282
  _globals['_VIEWRESPONSE']._serialized_start=284
  _globals['_VIEWRESPONSE']._serialized_end=328
  _globals['_GAMEENGINESERVICE']._serialized_start=330
  _globals['_GAMEENGINESERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
